CREATE TABLE SCHOOL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE STUDENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    school_id BIGINT NOT NULL,
    Name VARCHAR(30) NOT NULL,
    Surname VARCHAR(30) NOT NULL
);

ALTER TABLE STUDENT
    ADD CONSTRAINT school_student_id
    FOREIGN KEY (school_id) REFERENCES school(id)